[2024-06-12T08:37:37.707+0000] {processor.py:157} INFO - Started process (PID=32) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:37:37.707+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-12T08:37:37.709+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:37:37.708+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:37:37.885+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:37:37.882+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-12T08:37:37.885+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:37:37.897+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.192 seconds
[2024-06-12T08:38:08.069+0000] {processor.py:157} INFO - Started process (PID=41) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:38:08.070+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-12T08:38:08.071+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:38:08.071+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:38:08.183+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:38:08.181+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-12T08:38:08.184+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:38:08.195+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.127 seconds
[2024-06-12T08:38:38.533+0000] {processor.py:157} INFO - Started process (PID=51) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:38:38.533+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-12T08:38:38.534+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:38:38.534+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:38:38.636+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:38:38.634+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-12T08:38:38.636+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:38:38.645+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.114 seconds
[2024-06-12T08:39:08.969+0000] {processor.py:157} INFO - Started process (PID=60) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:39:08.970+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-12T08:39:08.971+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:39:08.971+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:39:09.067+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:39:09.066+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-12T08:39:09.068+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:39:09.076+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.109 seconds
[2024-06-12T08:39:39.389+0000] {processor.py:157} INFO - Started process (PID=70) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:39:39.390+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-12T08:39:39.391+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:39:39.391+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:39:39.539+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:39:39.536+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-12T08:39:39.539+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:39:39.553+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.166 seconds
[2024-06-12T08:40:09.855+0000] {processor.py:157} INFO - Started process (PID=80) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:40:09.855+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-12T08:40:09.857+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:40:09.856+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:40:09.962+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:40:09.961+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-12T08:40:09.963+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:40:09.972+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.119 seconds
[2024-06-12T08:40:40.276+0000] {processor.py:157} INFO - Started process (PID=90) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:40:40.277+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-12T08:40:40.278+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:40:40.278+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:40:40.377+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:40:40.375+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-12T08:40:40.377+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:40:40.386+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.112 seconds
[2024-06-12T08:41:10.700+0000] {processor.py:157} INFO - Started process (PID=100) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:41:10.700+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-12T08:41:10.702+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:41:10.702+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:41:10.816+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:41:10.813+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-12T08:41:10.817+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:41:10.825+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.129 seconds
[2024-06-12T08:41:41.152+0000] {processor.py:157} INFO - Started process (PID=110) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:41:41.152+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-12T08:41:41.153+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:41:41.153+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:41:41.253+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:41:41.252+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-12T08:41:41.253+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:41:41.261+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.112 seconds
[2024-06-12T08:42:11.580+0000] {processor.py:157} INFO - Started process (PID=120) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:42:11.581+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-12T08:42:11.582+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:42:11.582+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:42:11.717+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:42:11.716+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-12T08:42:11.718+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:42:11.727+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.150 seconds
[2024-06-12T08:42:42.041+0000] {processor.py:157} INFO - Started process (PID=130) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:42:42.042+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-12T08:42:42.043+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:42:42.043+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:42:42.148+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:42:42.146+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-12T08:42:42.148+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:42:42.156+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.116 seconds
[2024-06-12T08:43:12.521+0000] {processor.py:157} INFO - Started process (PID=140) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:43:12.522+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-12T08:43:12.524+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:43:12.523+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:43:12.641+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:43:12.639+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-12T08:43:12.641+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:43:12.649+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.130 seconds
[2024-06-12T08:43:42.978+0000] {processor.py:157} INFO - Started process (PID=149) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:43:42.979+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-12T08:43:42.980+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:43:42.980+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:43:43.080+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:43:43.079+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-12T08:43:43.080+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:43:43.089+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.112 seconds
[2024-06-12T08:44:13.493+0000] {processor.py:157} INFO - Started process (PID=159) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:44:13.497+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-12T08:44:13.499+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:44:13.499+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:44:13.650+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:44:13.648+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-12T08:44:13.650+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:44:13.658+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.168 seconds
[2024-06-12T08:45:46.625+0000] {processor.py:157} INFO - Started process (PID=162) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:45:46.625+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-12T08:45:46.626+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:45:46.626+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:45:46.775+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:45:46.774+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-12T08:45:46.775+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:45:46.788+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.166 seconds
[2024-06-12T08:47:50.040+0000] {processor.py:157} INFO - Started process (PID=172) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:47:50.043+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-12T08:47:50.044+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:47:50.044+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:47:50.213+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:47:50.211+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-12T08:47:50.213+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:47:50.230+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.194 seconds
[2024-06-12T08:50:26.474+0000] {processor.py:157} INFO - Started process (PID=182) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:50:26.478+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-12T08:50:26.480+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:50:26.479+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:50:26.704+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:50:26.698+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-12T08:50:26.704+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:50:26.722+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.251 seconds
[2024-06-12T08:53:07.457+0000] {processor.py:157} INFO - Started process (PID=192) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:53:07.458+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-12T08:53:07.459+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:53:07.458+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:53:07.568+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:53:07.566+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-12T08:53:07.568+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:53:07.577+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.121 seconds
[2024-06-12T08:53:37.899+0000] {processor.py:157} INFO - Started process (PID=202) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:53:37.900+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-12T08:53:37.901+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:53:37.901+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:53:38.009+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:53:38.008+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-12T08:53:38.010+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:53:38.019+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.121 seconds
[2024-06-12T08:54:08.375+0000] {processor.py:157} INFO - Started process (PID=211) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:54:08.375+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-12T08:54:08.376+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:54:08.376+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:54:08.477+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:54:08.476+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-12T08:54:08.477+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:54:08.485+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.112 seconds
[2024-06-12T08:54:38.814+0000] {processor.py:157} INFO - Started process (PID=221) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:54:38.815+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-12T08:54:38.816+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:54:38.816+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:54:38.925+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:54:38.923+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-12T08:54:38.925+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:54:38.936+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.123 seconds
[2024-06-12T08:55:09.256+0000] {processor.py:157} INFO - Started process (PID=231) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:55:09.256+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-12T08:55:09.257+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:55:09.257+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:55:09.360+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:55:09.359+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-12T08:55:09.360+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:55:09.369+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.115 seconds
[2024-06-12T08:55:39.721+0000] {processor.py:157} INFO - Started process (PID=241) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:55:39.722+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-12T08:55:39.723+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:55:39.723+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:55:39.824+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:55:39.823+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-12T08:55:39.824+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:55:39.832+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.113 seconds
[2024-06-12T08:56:10.172+0000] {processor.py:157} INFO - Started process (PID=258) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:56:10.173+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-12T08:56:10.174+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:56:10.174+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:56:10.277+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:56:10.276+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-12T08:56:10.277+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:56:10.286+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.116 seconds
[2024-06-12T08:56:40.620+0000] {processor.py:157} INFO - Started process (PID=268) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:56:40.621+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-12T08:56:40.622+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:56:40.622+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:56:40.719+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:56:40.718+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-12T08:56:40.720+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:56:40.727+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.109 seconds
[2024-06-12T08:57:11.073+0000] {processor.py:157} INFO - Started process (PID=278) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:57:11.073+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-12T08:57:11.074+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:57:11.074+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:57:11.179+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:57:11.178+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-12T08:57:11.179+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:57:11.188+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.117 seconds
[2024-06-12T08:57:41.540+0000] {processor.py:157} INFO - Started process (PID=287) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:57:41.541+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-12T08:57:41.542+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:57:41.542+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:57:41.640+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:57:41.639+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-12T08:57:41.641+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:57:41.656+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.117 seconds
[2024-06-12T08:58:11.948+0000] {processor.py:157} INFO - Started process (PID=297) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:58:11.948+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-12T08:58:11.949+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:58:11.949+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:58:12.048+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:58:12.047+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-12T08:58:12.048+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:58:12.057+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.110 seconds
[2024-06-12T08:58:42.407+0000] {processor.py:157} INFO - Started process (PID=307) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:58:42.408+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-12T08:58:42.409+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:58:42.409+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:58:42.508+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:58:42.507+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-12T08:58:42.508+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:58:42.517+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.112 seconds
[2024-06-12T08:59:12.842+0000] {processor.py:157} INFO - Started process (PID=317) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:59:12.842+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-12T08:59:12.843+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:59:12.843+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:59:12.947+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:59:12.945+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-12T08:59:12.948+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:59:12.957+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.116 seconds
[2024-06-12T08:59:43.301+0000] {processor.py:157} INFO - Started process (PID=326) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:59:43.302+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-12T08:59:43.303+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:59:43.303+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:59:43.402+0000] {logging_mixin.py:151} INFO - [2024-06-12T08:59:43.401+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-12T08:59:43.402+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T08:59:43.411+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.112 seconds
[2024-06-12T09:00:13.746+0000] {processor.py:157} INFO - Started process (PID=336) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:00:13.747+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-12T09:00:13.748+0000] {logging_mixin.py:151} INFO - [2024-06-12T09:00:13.748+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:00:13.877+0000] {logging_mixin.py:151} INFO - [2024-06-12T09:00:13.875+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-12T09:00:13.877+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:00:13.886+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.142 seconds
[2024-06-12T09:00:44.234+0000] {processor.py:157} INFO - Started process (PID=346) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:00:44.234+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-12T09:00:44.235+0000] {logging_mixin.py:151} INFO - [2024-06-12T09:00:44.235+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:00:44.342+0000] {logging_mixin.py:151} INFO - [2024-06-12T09:00:44.339+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-12T09:00:44.342+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:00:44.354+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.122 seconds
[2024-06-12T09:01:14.702+0000] {processor.py:157} INFO - Started process (PID=355) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:01:14.703+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-12T09:01:14.704+0000] {logging_mixin.py:151} INFO - [2024-06-12T09:01:14.704+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:01:14.806+0000] {logging_mixin.py:151} INFO - [2024-06-12T09:01:14.804+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-12T09:01:14.806+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:01:14.815+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.114 seconds
[2024-06-12T09:01:45.147+0000] {processor.py:157} INFO - Started process (PID=364) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:01:45.148+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-12T09:01:45.150+0000] {logging_mixin.py:151} INFO - [2024-06-12T09:01:45.150+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:01:45.264+0000] {logging_mixin.py:151} INFO - [2024-06-12T09:01:45.263+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-12T09:01:45.264+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:01:45.272+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.128 seconds
[2024-06-12T09:02:15.560+0000] {processor.py:157} INFO - Started process (PID=373) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:02:15.560+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-12T09:02:15.562+0000] {logging_mixin.py:151} INFO - [2024-06-12T09:02:15.562+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:02:15.712+0000] {logging_mixin.py:151} INFO - [2024-06-12T09:02:15.710+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-12T09:02:15.713+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:02:15.724+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.167 seconds
[2024-06-12T09:02:46.083+0000] {processor.py:157} INFO - Started process (PID=383) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:02:46.084+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-12T09:02:46.085+0000] {logging_mixin.py:151} INFO - [2024-06-12T09:02:46.084+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:02:46.200+0000] {logging_mixin.py:151} INFO - [2024-06-12T09:02:46.198+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-12T09:02:46.200+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:02:46.209+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.127 seconds
[2024-06-12T09:03:16.619+0000] {processor.py:157} INFO - Started process (PID=393) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:03:16.619+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-12T09:03:16.621+0000] {logging_mixin.py:151} INFO - [2024-06-12T09:03:16.621+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:03:16.730+0000] {logging_mixin.py:151} INFO - [2024-06-12T09:03:16.729+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-12T09:03:16.731+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:03:16.740+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.123 seconds
[2024-06-12T09:03:47.067+0000] {processor.py:157} INFO - Started process (PID=402) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:03:47.069+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-12T09:03:47.071+0000] {logging_mixin.py:151} INFO - [2024-06-12T09:03:47.071+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:03:47.178+0000] {logging_mixin.py:151} INFO - [2024-06-12T09:03:47.177+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-12T09:03:47.179+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:03:47.188+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.124 seconds
[2024-06-12T09:04:17.532+0000] {processor.py:157} INFO - Started process (PID=411) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:04:17.533+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-12T09:04:17.534+0000] {logging_mixin.py:151} INFO - [2024-06-12T09:04:17.534+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:04:17.644+0000] {logging_mixin.py:151} INFO - [2024-06-12T09:04:17.643+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-12T09:04:17.645+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:04:17.653+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.123 seconds
[2024-06-12T09:04:48.066+0000] {processor.py:157} INFO - Started process (PID=421) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:04:48.066+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-12T09:04:48.067+0000] {logging_mixin.py:151} INFO - [2024-06-12T09:04:48.067+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:04:48.191+0000] {logging_mixin.py:151} INFO - [2024-06-12T09:04:48.189+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-12T09:04:48.191+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:04:48.201+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.136 seconds
[2024-06-12T09:07:00.428+0000] {processor.py:157} INFO - Started process (PID=424) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:07:00.429+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-12T09:07:00.437+0000] {logging_mixin.py:151} INFO - [2024-06-12T09:07:00.436+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:07:00.712+0000] {logging_mixin.py:151} INFO - [2024-06-12T09:07:00.710+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-12T09:07:00.713+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:07:00.730+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.309 seconds
[2024-06-12T09:10:28.440+0000] {processor.py:157} INFO - Started process (PID=434) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:10:28.441+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-12T09:10:28.446+0000] {logging_mixin.py:151} INFO - [2024-06-12T09:10:28.446+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:10:28.740+0000] {logging_mixin.py:151} INFO - [2024-06-12T09:10:28.735+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-12T09:10:28.741+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:10:28.760+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.327 seconds
[2024-06-12T09:12:57.858+0000] {processor.py:157} INFO - Started process (PID=444) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:12:57.859+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-12T09:12:57.866+0000] {logging_mixin.py:151} INFO - [2024-06-12T09:12:57.866+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:12:58.132+0000] {logging_mixin.py:151} INFO - [2024-06-12T09:12:58.130+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-12T09:12:58.132+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:12:58.141+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.290 seconds
[2024-06-12T09:17:25.584+0000] {processor.py:157} INFO - Started process (PID=454) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:17:25.584+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-12T09:17:25.585+0000] {logging_mixin.py:151} INFO - [2024-06-12T09:17:25.585+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:17:25.689+0000] {logging_mixin.py:151} INFO - [2024-06-12T09:17:25.688+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-12T09:17:25.690+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:17:25.698+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.116 seconds
[2024-06-12T09:19:55.630+0000] {processor.py:157} INFO - Started process (PID=464) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:19:55.633+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-12T09:19:55.639+0000] {logging_mixin.py:151} INFO - [2024-06-12T09:19:55.639+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:19:55.788+0000] {logging_mixin.py:151} INFO - [2024-06-12T09:19:55.787+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-12T09:19:55.789+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:19:55.797+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.182 seconds
[2024-06-12T09:24:23.066+0000] {processor.py:157} INFO - Started process (PID=473) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:24:23.067+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-12T09:24:23.070+0000] {logging_mixin.py:151} INFO - [2024-06-12T09:24:23.069+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:24:23.335+0000] {logging_mixin.py:151} INFO - [2024-06-12T09:24:23.331+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-12T09:24:23.335+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:24:23.353+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.296 seconds
[2024-06-12T09:28:50.823+0000] {processor.py:157} INFO - Started process (PID=483) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:28:50.824+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-12T09:28:50.825+0000] {logging_mixin.py:151} INFO - [2024-06-12T09:28:50.825+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:28:50.933+0000] {logging_mixin.py:151} INFO - [2024-06-12T09:28:50.932+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-12T09:28:50.933+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:28:50.942+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.121 seconds
[2024-06-12T09:31:27.296+0000] {processor.py:157} INFO - Started process (PID=493) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:31:27.296+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-12T09:31:27.298+0000] {logging_mixin.py:151} INFO - [2024-06-12T09:31:27.298+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:31:27.410+0000] {logging_mixin.py:151} INFO - [2024-06-12T09:31:27.409+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-12T09:31:27.411+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:31:27.423+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.128 seconds
[2024-06-12T09:32:36.142+0000] {processor.py:157} INFO - Started process (PID=503) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:32:36.143+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-12T09:32:36.144+0000] {logging_mixin.py:151} INFO - [2024-06-12T09:32:36.144+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:32:36.244+0000] {logging_mixin.py:151} INFO - [2024-06-12T09:32:36.243+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-12T09:32:36.245+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:32:36.253+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.113 seconds
[2024-06-12T09:34:22.329+0000] {processor.py:157} INFO - Started process (PID=512) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:34:22.330+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-12T09:34:22.331+0000] {logging_mixin.py:151} INFO - [2024-06-12T09:34:22.331+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:34:22.432+0000] {logging_mixin.py:151} INFO - [2024-06-12T09:34:22.431+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-12T09:34:22.433+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T09:34:22.441+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.113 seconds
[2024-06-12T10:56:58.098+0000] {processor.py:157} INFO - Started process (PID=522) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T10:56:58.099+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-12T10:56:58.100+0000] {logging_mixin.py:151} INFO - [2024-06-12T10:56:58.100+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T10:56:58.211+0000] {logging_mixin.py:151} INFO - [2024-06-12T10:56:58.210+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-12T10:56:58.212+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T10:56:58.229+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.133 seconds
[2024-06-12T11:27:56.636+0000] {processor.py:157} INFO - Started process (PID=532) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T11:27:56.637+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-12T11:27:56.641+0000] {logging_mixin.py:151} INFO - [2024-06-12T11:27:56.641+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T11:27:56.758+0000] {logging_mixin.py:151} INFO - [2024-06-12T11:27:56.756+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-12T11:27:56.758+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T11:27:56.768+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.137 seconds
[2024-06-12T16:51:21.275+0000] {processor.py:157} INFO - Started process (PID=32) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T16:51:21.276+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-12T16:51:21.278+0000] {logging_mixin.py:151} INFO - [2024-06-12T16:51:21.278+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T16:51:21.464+0000] {logging_mixin.py:151} INFO - [2024-06-12T16:51:21.460+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-12T16:51:21.465+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-12T16:51:21.479+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.207 seconds
