[2024-06-07T00:03:45.791+0000] {processor.py:157} INFO - Started process (PID=832) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T00:03:45.792+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-07T00:03:45.796+0000] {logging_mixin.py:151} INFO - [2024-06-07T00:03:45.796+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T00:03:46.014+0000] {logging_mixin.py:151} INFO - [2024-06-07T00:03:46.009+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-07T00:03:46.014+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T00:03:46.035+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.250 seconds
[2024-06-07T00:21:22.330+0000] {processor.py:157} INFO - Started process (PID=842) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T00:21:22.332+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-07T00:21:22.335+0000] {logging_mixin.py:151} INFO - [2024-06-07T00:21:22.335+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T00:21:22.548+0000] {logging_mixin.py:151} INFO - [2024-06-07T00:21:22.546+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-07T00:21:22.551+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T00:21:22.570+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.243 seconds
[2024-06-07T00:56:05.625+0000] {processor.py:157} INFO - Started process (PID=852) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T00:56:05.626+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-07T00:56:05.630+0000] {logging_mixin.py:151} INFO - [2024-06-07T00:56:05.630+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T00:56:05.906+0000] {logging_mixin.py:151} INFO - [2024-06-07T00:56:05.901+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-07T00:56:05.907+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T00:56:05.938+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.318 seconds
[2024-06-07T01:04:43.686+0000] {processor.py:157} INFO - Started process (PID=861) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T01:04:43.686+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-07T01:04:43.687+0000] {logging_mixin.py:151} INFO - [2024-06-07T01:04:43.687+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T01:04:43.794+0000] {logging_mixin.py:151} INFO - [2024-06-07T01:04:43.792+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-07T01:04:43.794+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T01:04:43.809+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.125 seconds
[2024-06-07T01:09:18.601+0000] {processor.py:157} INFO - Started process (PID=871) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T01:09:18.603+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-07T01:09:18.607+0000] {logging_mixin.py:151} INFO - [2024-06-07T01:09:18.607+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T01:09:18.804+0000] {logging_mixin.py:151} INFO - [2024-06-07T01:09:18.802+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-07T01:09:18.805+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T01:09:18.822+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.224 seconds
[2024-06-07T01:43:31.856+0000] {processor.py:157} INFO - Started process (PID=881) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T01:43:31.856+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-07T01:43:31.863+0000] {logging_mixin.py:151} INFO - [2024-06-07T01:43:31.863+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T01:43:32.075+0000] {logging_mixin.py:151} INFO - [2024-06-07T01:43:32.073+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-07T01:43:32.075+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T01:43:32.100+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.249 seconds
[2024-06-07T02:00:28.321+0000] {processor.py:157} INFO - Started process (PID=891) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T02:00:28.322+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-07T02:00:28.324+0000] {logging_mixin.py:151} INFO - [2024-06-07T02:00:28.324+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T02:00:28.532+0000] {logging_mixin.py:151} INFO - [2024-06-07T02:00:28.530+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-07T02:00:28.534+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T02:00:28.550+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.234 seconds
[2024-06-07T02:05:48.319+0000] {processor.py:157} INFO - Started process (PID=901) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T02:05:48.320+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-07T02:05:48.322+0000] {logging_mixin.py:151} INFO - [2024-06-07T02:05:48.321+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T02:05:48.430+0000] {logging_mixin.py:151} INFO - [2024-06-07T02:05:48.429+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-07T02:05:48.430+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T02:05:48.438+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.122 seconds
[2024-06-07T02:38:16.502+0000] {processor.py:157} INFO - Started process (PID=911) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T02:38:16.503+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-07T02:38:16.506+0000] {logging_mixin.py:151} INFO - [2024-06-07T02:38:16.505+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T02:38:16.696+0000] {logging_mixin.py:151} INFO - [2024-06-07T02:38:16.695+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-07T02:38:16.697+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T02:38:16.720+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.221 seconds
[2024-06-07T02:54:38.384+0000] {processor.py:157} INFO - Started process (PID=921) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T02:54:38.385+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-07T02:54:38.386+0000] {logging_mixin.py:151} INFO - [2024-06-07T02:54:38.386+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T02:54:38.492+0000] {logging_mixin.py:151} INFO - [2024-06-07T02:54:38.491+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-07T02:54:38.492+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T02:54:38.501+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.118 seconds
[2024-06-07T03:06:46.809+0000] {processor.py:157} INFO - Started process (PID=931) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T03:06:46.810+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-07T03:06:46.811+0000] {logging_mixin.py:151} INFO - [2024-06-07T03:06:46.811+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T03:06:46.923+0000] {logging_mixin.py:151} INFO - [2024-06-07T03:06:46.922+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-07T03:06:46.923+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T03:06:46.931+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.124 seconds
[2024-06-07T03:38:46.588+0000] {processor.py:157} INFO - Started process (PID=941) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T03:38:46.589+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-07T03:38:46.590+0000] {logging_mixin.py:151} INFO - [2024-06-07T03:38:46.590+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T03:38:46.691+0000] {logging_mixin.py:151} INFO - [2024-06-07T03:38:46.690+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-07T03:38:46.691+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T03:38:46.699+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.113 seconds
[2024-06-07T03:54:57.873+0000] {processor.py:157} INFO - Started process (PID=951) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T03:54:57.873+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-07T03:54:57.875+0000] {logging_mixin.py:151} INFO - [2024-06-07T03:54:57.874+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T03:54:57.982+0000] {logging_mixin.py:151} INFO - [2024-06-07T03:54:57.981+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-07T03:54:57.982+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T03:54:57.991+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.120 seconds
[2024-06-07T04:07:46.633+0000] {processor.py:157} INFO - Started process (PID=961) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T04:07:46.637+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-07T04:07:46.639+0000] {logging_mixin.py:151} INFO - [2024-06-07T04:07:46.639+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T04:07:46.782+0000] {logging_mixin.py:151} INFO - [2024-06-07T04:07:46.781+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-07T04:07:46.782+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T04:07:46.790+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.159 seconds
[2024-06-07T04:40:00.685+0000] {processor.py:157} INFO - Started process (PID=971) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T04:40:00.686+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-07T04:40:00.690+0000] {logging_mixin.py:151} INFO - [2024-06-07T04:40:00.690+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T04:40:00.907+0000] {logging_mixin.py:151} INFO - [2024-06-07T04:40:00.902+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-07T04:40:00.908+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T04:40:00.926+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.247 seconds
[2024-06-07T04:55:50.675+0000] {processor.py:157} INFO - Started process (PID=981) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T04:55:50.675+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-07T04:55:50.677+0000] {logging_mixin.py:151} INFO - [2024-06-07T04:55:50.677+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T04:55:50.782+0000] {logging_mixin.py:151} INFO - [2024-06-07T04:55:50.781+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-07T04:55:50.783+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T04:55:50.791+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.119 seconds
[2024-06-07T05:08:43.242+0000] {processor.py:157} INFO - Started process (PID=991) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T05:08:43.247+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-07T05:08:43.252+0000] {logging_mixin.py:151} INFO - [2024-06-07T05:08:43.252+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T05:08:43.464+0000] {logging_mixin.py:151} INFO - [2024-06-07T05:08:43.462+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-07T05:08:43.465+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T05:08:43.497+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.265 seconds
[2024-06-07T05:40:52.477+0000] {processor.py:157} INFO - Started process (PID=1000) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T05:40:52.478+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-07T05:40:52.479+0000] {logging_mixin.py:151} INFO - [2024-06-07T05:40:52.479+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T05:40:52.582+0000] {logging_mixin.py:151} INFO - [2024-06-07T05:40:52.581+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-07T05:40:52.582+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T05:40:52.590+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.115 seconds
[2024-06-07T05:58:35.498+0000] {processor.py:157} INFO - Started process (PID=1009) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T05:58:35.501+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-07T05:58:35.506+0000] {logging_mixin.py:151} INFO - [2024-06-07T05:58:35.505+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T05:58:35.719+0000] {logging_mixin.py:151} INFO - [2024-06-07T05:58:35.716+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-07T05:58:35.722+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T05:58:35.750+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.255 seconds
[2024-06-07T06:09:41.144+0000] {processor.py:157} INFO - Started process (PID=1019) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T06:09:41.145+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-07T06:09:41.148+0000] {logging_mixin.py:151} INFO - [2024-06-07T06:09:41.148+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T06:09:41.382+0000] {logging_mixin.py:151} INFO - [2024-06-07T06:09:41.379+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-07T06:09:41.382+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T06:09:41.404+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.267 seconds
[2024-06-07T06:31:48.182+0000] {processor.py:157} INFO - Started process (PID=1029) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T06:31:48.183+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-07T06:31:48.184+0000] {logging_mixin.py:151} INFO - [2024-06-07T06:31:48.183+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T06:31:48.286+0000] {logging_mixin.py:151} INFO - [2024-06-07T06:31:48.285+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-07T06:31:48.286+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T06:31:48.294+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.114 seconds
[2024-06-07T07:10:21.307+0000] {processor.py:157} INFO - Started process (PID=1039) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:10:21.309+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-07T07:10:21.315+0000] {logging_mixin.py:151} INFO - [2024-06-07T07:10:21.315+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:10:21.604+0000] {logging_mixin.py:151} INFO - [2024-06-07T07:10:21.602+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-07T07:10:21.605+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:10:21.630+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.337 seconds
[2024-06-07T07:21:46.543+0000] {processor.py:157} INFO - Started process (PID=1048) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:21:46.546+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-07T07:21:46.548+0000] {logging_mixin.py:151} INFO - [2024-06-07T07:21:46.548+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:21:46.858+0000] {logging_mixin.py:151} INFO - [2024-06-07T07:21:46.855+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-07T07:21:46.859+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:21:46.890+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.352 seconds
[2024-06-07T07:22:17.188+0000] {processor.py:157} INFO - Started process (PID=1058) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:22:17.188+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-07T07:22:17.189+0000] {logging_mixin.py:151} INFO - [2024-06-07T07:22:17.189+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:22:17.299+0000] {logging_mixin.py:151} INFO - [2024-06-07T07:22:17.298+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-07T07:22:17.300+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:22:17.309+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.123 seconds
[2024-06-07T07:22:47.674+0000] {processor.py:157} INFO - Started process (PID=1068) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:22:47.675+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-07T07:22:47.676+0000] {logging_mixin.py:151} INFO - [2024-06-07T07:22:47.676+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:22:47.789+0000] {logging_mixin.py:151} INFO - [2024-06-07T07:22:47.788+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-07T07:22:47.789+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:22:47.799+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.126 seconds
[2024-06-07T07:23:18.113+0000] {processor.py:157} INFO - Started process (PID=1078) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:23:18.113+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-07T07:23:18.114+0000] {logging_mixin.py:151} INFO - [2024-06-07T07:23:18.114+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:23:18.218+0000] {logging_mixin.py:151} INFO - [2024-06-07T07:23:18.217+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-07T07:23:18.219+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:23:18.228+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.117 seconds
[2024-06-07T07:23:48.542+0000] {processor.py:157} INFO - Started process (PID=1088) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:23:48.543+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-07T07:23:48.544+0000] {logging_mixin.py:151} INFO - [2024-06-07T07:23:48.544+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:23:48.649+0000] {logging_mixin.py:151} INFO - [2024-06-07T07:23:48.648+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-07T07:23:48.650+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:23:48.659+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.119 seconds
[2024-06-07T07:24:18.940+0000] {processor.py:157} INFO - Started process (PID=1098) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:24:18.940+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-07T07:24:18.941+0000] {logging_mixin.py:151} INFO - [2024-06-07T07:24:18.941+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:24:19.045+0000] {logging_mixin.py:151} INFO - [2024-06-07T07:24:19.044+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-07T07:24:19.046+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:24:19.054+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.116 seconds
[2024-06-07T07:24:49.387+0000] {processor.py:157} INFO - Started process (PID=1107) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:24:49.387+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-07T07:24:49.388+0000] {logging_mixin.py:151} INFO - [2024-06-07T07:24:49.388+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:24:49.491+0000] {logging_mixin.py:151} INFO - [2024-06-07T07:24:49.490+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-07T07:24:49.491+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:24:49.500+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.115 seconds
[2024-06-07T07:25:19.826+0000] {processor.py:157} INFO - Started process (PID=1116) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:25:19.827+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-07T07:25:19.828+0000] {logging_mixin.py:151} INFO - [2024-06-07T07:25:19.828+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:25:19.940+0000] {logging_mixin.py:151} INFO - [2024-06-07T07:25:19.939+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-07T07:25:19.941+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:25:19.950+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.125 seconds
[2024-06-07T07:25:50.258+0000] {processor.py:157} INFO - Started process (PID=1125) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:25:50.258+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-07T07:25:50.259+0000] {logging_mixin.py:151} INFO - [2024-06-07T07:25:50.259+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:25:50.373+0000] {logging_mixin.py:151} INFO - [2024-06-07T07:25:50.372+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-07T07:25:50.373+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:25:50.383+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.127 seconds
[2024-06-07T07:26:20.653+0000] {processor.py:157} INFO - Started process (PID=1135) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:26:20.654+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-07T07:26:20.655+0000] {logging_mixin.py:151} INFO - [2024-06-07T07:26:20.655+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:26:20.767+0000] {logging_mixin.py:151} INFO - [2024-06-07T07:26:20.766+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-07T07:26:20.767+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:26:20.776+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.125 seconds
[2024-06-07T07:26:51.096+0000] {processor.py:157} INFO - Started process (PID=1144) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:26:51.097+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-07T07:26:51.098+0000] {logging_mixin.py:151} INFO - [2024-06-07T07:26:51.098+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:26:51.211+0000] {logging_mixin.py:151} INFO - [2024-06-07T07:26:51.210+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-07T07:26:51.212+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:26:51.221+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.126 seconds
[2024-06-07T07:27:21.504+0000] {processor.py:157} INFO - Started process (PID=1154) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:27:21.504+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-07T07:27:21.506+0000] {logging_mixin.py:151} INFO - [2024-06-07T07:27:21.506+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:27:21.611+0000] {logging_mixin.py:151} INFO - [2024-06-07T07:27:21.610+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-07T07:27:21.612+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:27:21.621+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.119 seconds
[2024-06-07T07:27:51.903+0000] {processor.py:157} INFO - Started process (PID=1164) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:27:51.904+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-07T07:27:51.905+0000] {logging_mixin.py:151} INFO - [2024-06-07T07:27:51.905+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:27:52.011+0000] {logging_mixin.py:151} INFO - [2024-06-07T07:27:52.010+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-07T07:27:52.011+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:27:52.020+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.118 seconds
[2024-06-07T07:28:22.354+0000] {processor.py:157} INFO - Started process (PID=1173) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:28:22.355+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-07T07:28:22.356+0000] {logging_mixin.py:151} INFO - [2024-06-07T07:28:22.356+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:28:22.464+0000] {logging_mixin.py:151} INFO - [2024-06-07T07:28:22.463+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-07T07:28:22.464+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:28:22.472+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.120 seconds
[2024-06-07T07:28:52.803+0000] {processor.py:157} INFO - Started process (PID=1182) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:28:52.804+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-07T07:28:52.805+0000] {logging_mixin.py:151} INFO - [2024-06-07T07:28:52.805+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:28:52.910+0000] {logging_mixin.py:151} INFO - [2024-06-07T07:28:52.909+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-07T07:28:52.910+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:28:52.919+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.118 seconds
[2024-06-07T07:29:23.207+0000] {processor.py:157} INFO - Started process (PID=1192) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:29:23.208+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-07T07:29:23.209+0000] {logging_mixin.py:151} INFO - [2024-06-07T07:29:23.209+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:29:23.331+0000] {logging_mixin.py:151} INFO - [2024-06-07T07:29:23.329+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-07T07:29:23.331+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:29:23.342+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.136 seconds
[2024-06-07T07:29:53.619+0000] {processor.py:157} INFO - Started process (PID=1209) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:29:53.620+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-07T07:29:53.621+0000] {logging_mixin.py:151} INFO - [2024-06-07T07:29:53.621+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:29:53.725+0000] {logging_mixin.py:151} INFO - [2024-06-07T07:29:53.724+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-07T07:29:53.725+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:29:53.734+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.117 seconds
[2024-06-07T07:30:24.027+0000] {processor.py:157} INFO - Started process (PID=1218) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:30:24.028+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-07T07:30:24.029+0000] {logging_mixin.py:151} INFO - [2024-06-07T07:30:24.029+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:30:24.136+0000] {logging_mixin.py:151} INFO - [2024-06-07T07:30:24.135+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-07T07:30:24.136+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:30:24.145+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.119 seconds
[2024-06-07T07:30:54.456+0000] {processor.py:157} INFO - Started process (PID=1228) to work on /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:30:54.457+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fetch_from_data_sources.py for tasks to queue
[2024-06-07T07:30:54.458+0000] {logging_mixin.py:151} INFO - [2024-06-07T07:30:54.458+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:30:54.580+0000] {logging_mixin.py:151} INFO - [2024-06-07T07:30:54.579+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/fetch_from_data_sources.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fetch_from_data_sources.py", line 4, in <module>
    from stations_functions import kafka_fct, fetch_and_insert_into_elasticsearch_emplacement_stations, fetch_and_insert_into_elasticsearch_perim, elastic_metro_station
ImportError: cannot import name 'kafka_fct' from 'stations_functions' (/opt/airflow/dags/stations_functions.py)
[2024-06-07T07:30:54.581+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fetch_from_data_sources.py
[2024-06-07T07:30:54.590+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fetch_from_data_sources.py took 0.136 seconds
